
language: python

python:
  - 3.7

script:
  - pip install file://$(pwd)

deploy:
  provider: pypi
  user: mottosso
  distributions: "sdist bdist_wheel"
  password:
    secure: Jp1pjTdR14zMCbr5UnS3HGZyFPtwx544h0eIL9eepnAHe2maqzNLhhDXSySvYOwq4BmOxy1zSwnoNGrIKv9Zl5Pl48T8tKH9RCbzYEvxG+aeBtMz3YclPchNuT4mp+aRT6IEIShJIYtIKgoo02S0ObwKO5zCz10NAwCcZbcYKIo=
  on:
    tags: true
    repo: pyblish/pyblish-photoshop
